1.#CREAR UN PROGRAMA QUE BUSQUE EN EL PENSAMIENTO DE CESAR ACUÑA LA PALABRA POLITICOS .
#HAY POLITICOS QUE NO HACEN NADA POR QUE NUNCA HAN HECHO NADA
# Y MOSTRARLO POR TERMINAL SI LO ENCUENTRA

pensamiento_uno:str="HAY POLITICOS QUE NO HACEN NADA POR QUE NUNCA HAN HECHO"
palabra_buscar="POLITICOS"
print("POLITICOS" if pensamiento_uno.find(palabra_buscar)>0 else "texto no encontrado")



2. #CREAR UN PROGRAMA QUE EN EL SIGUIENTE TEXTO 'YO YA NO VIVO EN TRUJILIO,VIVO EN PERU'
#.BUSQUE PERU Y LO REMPLAZE POR NARNIA.FINALMENTE MOSTRARLO POR TERMINAL  

pensamiento_dos:str="YO YA NO VIVO EN TRUJILIO,VIVO EN PERU"
print(pensamiento_dos)
print(pensamiento_dos.replace("PERU","NARNIA"))
